---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-signup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-signup
  template:
    metadata:
      labels:
        app: backend-signup
    spec:
      containers:
      - name: backend-signup
        image: chris4929/webback2:signup
        ports:
        - containerPort: 5011