---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-signin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-signin
  template:
    metadata:
      labels:
        app: backend-signin
    spec:
      containers:
      - name: backend-signin
        image: chris4929/webback:3.0
        ports:
        - containerPort: 5012