---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-interpret
spec:
  selector:
    app: backend-interpret
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
  type: ClusterIP