---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-preprocess
spec:
  selector:
    app: backend-preprocess
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP