---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-records
spec:
  selector:
    app: backend-records
  ports:
    - protocol: TCP
      port: 5007
      targetPort: 5007
  type: ClusterIP