---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-signup
spec:
  selector:
    app: backend-signup
  ports:
    - protocol: TCP
      port: 5011
      targetPort: 5011
  type: ClusterIP