---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-upload
spec:
  selector:
    app: backend-upload
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
